name: daily
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  animated_list_plus: ^0.5.0
  collapsible_sidebar: ^2.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  go_router: ^6.5.6
  hooks_riverpod: ^2.3.6
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  riverpod: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
